/*
    anlut: ancc look up table
    Aean, 2014.6.29
*/

#include "ancc.h"

/* == Keyword list. =============================== */
keyword_t keylist[] = {
    {"auto"         ,  K_AUTO},
    {"break"        ,  K_BREAK},
    {"case"         ,  K_CASE},
    {"char"         ,  K_CHAR},
    {"const"        ,  K_CONST},
    {"continue"     ,  K_CONTINUE},
    {"default"      ,  K_DEFAULT},
    {"do"           ,  K_DO},
    {"double"       ,  K_DOUBLE},
    {"else"         ,  K_ELSE},
    {"enum"         ,  K_ENUM},
    {"extern"       ,  K_EXTERN},
    {"float"        ,  K_FLOAT},
    {"for"          ,  K_FOR},
    {"goto"         ,  K_GOTO},
    {"if"           ,  K_IF},
    {"inline"       ,  K_INLINE},
    {"int"          ,  K_INT},
    {"long"         ,  K_LONG},
    {"register"     ,  K_REGISTER},
    {"restrict"     ,  K_RESTRICT},
    {"return"       ,  K_RETURN},
    {"short"        ,  K_SHORT},
    {"signed"       ,  K_SIGNED},
    {"sizeof"       ,  K_SIZEOF},
    {"static"       ,  K_STATIC},
    {"struct"       ,  K_STRUCT},
    {"switch"       ,  K_SWITCH},
    {"typedef"      ,  K_TYPEDEF},
    {"union"        ,  K_UNION},
    {"unsigned"     ,  K_UNSIGNED},
    {"void"         ,  K_VOID},
    {"volatile"     ,  K_VOLATILE},
    {"while"        ,  K_WHILE},
    {"_Bool"        ,  K_BOOL},
    {"_Complex"     ,  K_COMPLEX},
    {"_Imaginary"   ,  K_IMAGINARY},
    {"["            ,  PUNC1},
    {"]"            ,  PUNC2},
    {"("            ,  PUNC3},
    {")"            ,  PUNC4},
    {"{"            ,  PUNC5},
    {"}"            ,  PUNC6},
    {"."            ,  PUNC7},
    {"->"           ,  PUNC8},
    {"++"           ,  PUNC9},
    {"--"           ,  PUNC10},
    {"&"            ,  PUNC11},
    {"*"            ,  PUNC12},
    {"+"            ,  PUNC13},
    {"-"            ,  PUNC14},
    {"~"            ,  PUNC15},
    {"!"            ,  PUNC16},
    {"/"            ,  PUNC17},
    {"%"            ,  PUNC18},
    {"<<"           ,  PUNC19},
    {">>"           ,  PUNC20},
    {"<"            ,  PUNC21},
    {">"            ,  PUNC22},
    {"<="           ,  PUNC23},
    {">="           ,  PUNC24},
    {"=="           ,  PUNC25},
    {"!="           ,  PUNC26},
    {"^"            ,  PUNC27},
    {"|"            ,  PUNC28},
    {"&&"           ,  PUNC29},
    {"||"           ,  PUNC30},
    {"?"            ,  PUNC31},
    {":"            ,  PUNC32},
    {";"            ,  PUNC33},
    {"..."          ,  PUNC34},
    {"="            ,  PUNC35},
    {"*="           ,  PUNC36},
    {"/="           ,  PUNC37},
    {"%="           ,  PUNC38},
    {"+="           ,  PUNC39},
    {"-="           ,  PUNC40},
    {"<<="          ,  PUNC41},
    {">>="          ,  PUNC42},
    {"&="           ,  PUNC43},
    {"^="           ,  PUNC44},
    {"|="           ,  PUNC45},
    {","            ,  PUNC46},
    {"#"            ,  PUNC47},
    {"##"           ,  PUNC48},
    {"<:"           ,  PUNC1},
    {":>"           ,  PUNC2},
    {"<%"           ,  PUNC5},
    {"%>"           ,  PUNC6},
    {"%:"           ,  PUNC47},
    {"%:%:"         ,  PUNC48},
    {NULL           ,  NAL}
};
